services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5221:80
      - 7217:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecretPassword69
      - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
        
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecretDbPassword1337!